on:
  push:
    branches:
    - main
    - dockerfile
    tags:
    - v*
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: run linter
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./ v1.46.2
        make lint PATH=$PATH:`pwd`
  build:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
    - name: install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16.3
    - name: checkout code
      uses: actions/checkout@v2
    - name: test
      run: |
        make test
    - name: build
      id: build
      run: |
        version=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
        make build VERSION="${version}"
        echo "::set-output name=version::${version}"
  image:
    if: ${{ startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/dockerfile' }}
    needs:
    - lint
    - build
    runs-on: ubuntu-22.04
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - run: make image VERSION=${{ needs.build.outputs.version }}
  release:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    needs:
    - image
    runs-on: ubuntu-22.04
    steps:
    - name: install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16.3
    - name: checkout code
      uses: actions/checkout@v2
    - name: release
      run: |
        make release VERSION=${{ needs.build.outputs.version }}
    - name: publish
      if: ${{ success() }}
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: |
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-darwin-amd64-${{ needs.build.outputs.version }}.tar.gz
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-darwin-amd64-${{ needs.build.outputs.version }}.tar.gz.sha256
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-darwin-arm64-${{ needs.build.outputs.version }}.tar.gz
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-darwin-arm64-${{ needs.build.outputs.version }}.tar.gz.sha256
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-linux-amd64-${{ needs.build.outputs.version }}.tar.gz
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-linux-amd64-${{ needs.build.outputs.version }}.tar.gz.sha256
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-windows-amd64-${{ needs.build.outputs.version }}.tar.gz
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-windows-amd64-${{ needs.build.outputs.version }}.tar.gz.sha256
          target/releases/${{ needs.build.outputs.version }}/promdump
          target/releases/${{ needs.build.outputs.version }}/promdump.sha256
    - name: krew-index
      if: ${{ success() }}
      uses: rajatjindal/krew-release-bot@v0.0.43
      with:
        krew_template_file: plugins/promdump.yaml
