on:
  push:
    branches:
    - main
    tags:
    - v*
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: run linter
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./ v1.31.0
        make lint PATH=$PATH:`pwd`
  build:
    runs-on: ubuntu-18.04
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
    - name: install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
    - name: checkout code
      uses: actions/checkout@v2
    - name: test
      run: |
        make test
    - name: build
      id: build
      run: |
        version=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
        make build VERSION="${version}"
        echo "::set-output name=version::${version}"
  release:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    needs:
    - lint
    - build
    runs-on: ubuntu-18.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
    - name: install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
    - name: checkout code
      uses: actions/checkout@v2
    - name: release
      run: |
        make release VERSION=${{ needs.build.outputs.version }}
    - name: publish
      if: ${{ success() }}
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: |
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-darwin-amd64-${{ needs.build.outputs.version }}.tar.gz
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-darwin-amd64-${{ needs.build.outputs.version }}.tar.gz.sha256
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-linux-amd64-${{ needs.build.outputs.version }}.tar.gz
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-linux-amd64-${{ needs.build.outputs.version }}.tar.gz.sha256
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-windows-amd64-${{ needs.build.outputs.version }}.tar.gz
          target/releases/${{ needs.build.outputs.version }}/plugins/kubectl-promdump-windows-amd64-${{ needs.build.outputs.version }}.tar.gz.sha256
          target/releases/${{ needs.build.outputs.version }}/promdump
          target/releases/${{ needs.build.outputs.version }}/promdump.sha256
